
language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-27.0.3
    - tools
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
cache:
  directories:
    - $HOME/android-sdk-dl
    - $HOME/android-sdk
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_install:
    - chmod +x ./gradlew
    - yes | sdkmanager "platforms;android-27"
script:
  - ./gradlew testMockDebugUnit
